version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: /backend/build/package/Dockerfile
    ports:
      - "8080:8080"
  
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend