version: '3.8'

services:
  backend:
    build: 
      context: /backend
      dockerfile: /build/package/Dockerfile
    ports:
      - "8080:8080"
  
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend