services:
  backend:
    build: 
      context: ./backend
      dockerfile: ./build/package/Dockerfile
    networks:
      - app-network

  varnish:
    image: varnish:7.4
    ports:
      - "80:80"
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    networks:
    - app-network
    depends_on:
    - backend
  
  frontend:
    build: ./frontend
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - ./frontend/certbot:/etc/letsencrypt
    networks:
      - app-network
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./frontend/certbot:/etc/letsencrypt
    command: certonly --standalone -d intern-3.it-all-stars.com --email maxim_zheribor@dotwrk.com --agree-tos --non-interactive
    depends_on:
      - frontend

networks:
  app-network:
    driver: bridge